### PR TITLE
Fix: Able to throw multiple times

### LINKED ISSUE #28: Fix: Continuous Throw
Criteria:
- You should only be able to throw it again once it stops moving

### PR DESCRIPTION
**Pull request by ThijsvanDijk**
## Description
Fixed issues with being able to throw the block multiple times even while in the air

## Setting up testing environment
1. In the project window navigate to Project/Assets/Scenes and open "Collision fixes" scene.
2. Press Play.

#### Testing fixes
Criteria:
- [x] While in the air, you can not throw a second time

## Checklist
_These checks should always be true for your pull request_
- [x] My pull request is for one story/feature.
- [x] Every individual commit in this pull request is logical.
- [x] All code, documentation, commits and player seen texts are in English.
- [x] I have deleted unused / unnecessary code.
- [x] If my edits need a change in documentation, then I have updated the documentation.
- [x] All code is in correspondence with the code conventions.fixed issues with possessable objects going through the map

### CODE REVIEW

File: Assets/Scripts/Possession/Throwable.cs [hunk 1]
```diff
@@ -10,6 +8,9 @@ public class Throwable : MonoBehaviour, IPossessable
     [SerializeField] [Tooltip("Extra sensitivity on y-axis for easier throwing")] private float ySense = 2;
     [SerializeField] private float _rotationSpeed = 10;
     [SerializeField] [Tooltip("Minimum Impulse needed to destroy the object")] private float _destroyMinimumImpulse = 1;
+    [SerializeField]
+    [Tooltip("The maximum speed the object is allowed to go before being throwable again")]
+    private float _maxThrowSpeed = 5f;
```
Comment (Jeroenvn) [inline Assets/Scripts/Possession/Throwable.cs]: the name _maxThrowSpeed sound like it's the maximum strength to throw an object. Please rename it to something like _notThrowableThreshold.

File: Assets/Scripts/Possession/Throwable.cs [hunk 2]
```diff
@@ -93,7 +93,11 @@ public void Unpossess()
 
     private void ThrowObject()
     {
-        _rb.AddForce(_aim * _throwForce, ForceMode.Impulse);
+        
+        if(_rb.velocity.magnitude < _maxThrowSpeed)
```
Comment (Jeroenvn) [inline Assets/Scripts/Possession/Throwable.cs]: This only checks your speed which doesn't account for low speeds while in the air. I suggest adding some form of grounded check.

File: Assets/Scripts/Possession/Throwable.cs [hunk 3]
```diff
@@ -93,7 +93,11 @@ public void Unpossess()
 
     private void ThrowObject()
     {
-        _rb.AddForce(_aim * _throwForce, ForceMode.Impulse);
+
```
Comment (Jeroenvn) [inline Assets/Scripts/Possession/Throwable.cs:57]: whitespace

**Review by Jeroenvn — CHANGES_REQUESTED** [review]
I can still throw the object if the speed is low enough. A comment that I could not add is that the script contains a collider that is unused. There are also some other small issues that I've commented.

File: Assets/Scripts/Possession/Throwable.cs [hunk 4]
```diff
@@ -10,6 +8,9 @@ public class Throwable : MonoBehaviour, IPossessable
     [SerializeField] [Tooltip("Extra sensitivity on y-axis for easier throwing")] private float ySense = 2;
     [SerializeField] private float _rotationSpeed = 10;
     [SerializeField] [Tooltip("Minimum Impulse needed to destroy the object")] private float _destroyMinimumImpulse = 1;
+    [SerializeField]
+    [Tooltip("The maximum speed the object is allowed to go before being throwable again")]
+    private float _notThrowableThresholdSpeed = 5f;
```
Comment (Jeroenvn) [inline Assets/Scripts/Possession/Throwable.cs]: this variable is unused

**Review by Jeroenvn — CHANGES_REQUESTED** [review]
Looks good, except you didnt remove the _notThrowableThresholdSpeed when it isn't used

**Review by Jeroenvn — APPROVED** [review]
Looks good!
